name: Deploy documentation

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal:latest-alpine

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: "Install shards"
        run: shards install --ignore-crystal-version

      - name: "Generate docs"
        run: crystal docs --project-name=Spark --project-version=${{ github.ref }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
